Default: &defaults
  database: ygruq.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ygruq_test.sqlite3
  <<: *defaults

Staging:
  database: ygruq_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ygruq_production.sqlite3
  poolsize: 100
  <<: *defaults
